version: '3.8'

services:
  market_app:
    build:
      context: ./MarketApp-NextJs
    ports:
      - "3000:3000"
    env_file:
      - ./MarketApp-NextJs/.env

  prices_api:
    build:
      context: ./Prices_API-Go
    ports:
      - "3001:3001"
    env_file:
      - ./Prices_API-Go/.env

  shops_api:
    build:
      context: ./Shops_API-NestJS
    ports:
      - "3002:3002"
    env_file:
      - ./Shops_API-NestJS/.env
