version: '3.8'

services:
  market_app:
    build:
      context: ./MarketApp
    ports:
      - "3000:3000"
    env_file:
      - ./MarketApp/.env

  prices_api:
    build:
      context: ./PriceAPI
    ports:
      - "3001:3001"
    env_file:
      - ./PriceAPI/.env

  shops_api:
    build:
      context: ./ShopAPI
    ports:
      - "3002:3002"
    env_file:
      - ./ShopAPI/.env
