apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopsapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopsapi-nestjs
  template:
    metadata:
      labels:
        app: shopsapi-nestjs
    spec:
      containers:
        - name: shopsapi-container
          image: ghcr.io/wiktorb2004/shops_api-nestjs:master
          envFrom:
            - secretRef:
                name: shops-secret
          ports:
            - containerPort: 3002
          imagePullPolicy: Always
