apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketapp-nextjs
  template:
    metadata:
      labels:
        app: marketapp-nextjs
    spec:
      containers:
        - name: marketapp-container
          image: ghcr.io/wiktorb2004/marketapp-cicd_kubernetes/marketapp:master
          envFrom:
            - secretRef:
                name: market-secret
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
